env:
  TERM: xterm-256color

# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x24283b'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x9699a8'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'
window:
  # opacity: 0.95
  decorations: None
  padding:
    x: 4
    y: 4
  dynamic_padding: true

mouse:
  hide_when_typing: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

cursor:
  style: Beam
  unfocused_hollow: true

live_config_reload: true

font:
  normal:
    family: DejaVuSansMono
    style: Regular
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  AppleFontSmoothing: true
  draw_bold_text_with_bright_colors: true

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

scrolling:
  history: 1000

# key_bindings:
#   - { key: J, mods: Control, action: ScrollPageDown }
#   - { key: K, mods: Control, action: ScrollPageUp }
